[package]
name = "kecerahan-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
docopt = "1.1.0"
libc = "0.2.119"
serde = "1.0"
serde_derive = "1.0"
glob = "0.3.0"
